---
- name: configure banners and loopback descriptions
  hosts: lab
  gather_facts: no
  tasks:
    - name: configure login banners
      ios_banner:
        banner: login
        text: |
          Welcome to the Lab!
        state: present

    - name: add loopback interface descriptions
      ios_interfaces:
        config:
          - name: Loopback0
            description: 'Interface created using Ansible'
        state: merged

- name: configure vlans
  hosts: switches
  gather_facts: no
  tasks:
    - name: add vlan 10 and 20
      ios_vlans:
        config:
          - name: Accounting
            vlan_id: 10
          - name: Sales
            vlan_id: 20

- name: assign vlan to ports
  hosts: accessswitches
  gather_facts: no
  tasks:
    - name: assign vlan 10 to GigabitEthernet 0/1
      ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 10
        parents: interface GigabitEthernet 0/1

    - name: assign vlan 20 to GigabitEthernet 0/2
      ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 20
        parents: interface GigabitEthernet 0/2

- name: configure router on a stick
  hosts: routers
  gather_facts: no
  tasks:
    - name: configure GigabitEthernet 0/0.10
      ios_config:
        lines:
          - encapsulation dot1q 10
          - ip address 10.0.10.1 255.255.255.0
        parents: interface GigabitEthernet 0/0.10

    - name: configure GigabitEthernet 0/0.20
      ios_config:
        lines:
          - encapsulation dot1q 20
          - ip address 10.0.20.1 255.255.255.0
        parents: interface GigabitEthernet 0/0.20
...