---
- name: configure banners and loopback descriptions
  hosts: lab
  gather_facts: no
  tasks:
    - name: configure login banners
      ios_banner:
        banner: login
        text: |
          Welcome to the Lab!
        state: present

    - name: add loopback interface descriptions
      ios_interfaces:
        config:
          - name: Loopback0
            description: 'Interface created using Ansible'
        state: merged

- name: configure vlans
  hosts: switches
  gather_facts: no
  tasks:
    - name: add vlan 10 and 20
      ios_vlans:
        config:
          - name: Accounting
            vlan_id: 10
          - name: Sales
            vlan_id: 20
...