---
- name: remove banners and loopback interface descriptions
  hosts: lab
  gather_facts: no
  tasks:
    - name: remove login banners
      ios_banner:
        banner: login
        state: absent

    - name: remove loopback interface descriptions
      ios_config:
        lines: no description
        parents: interface Loopback0

- name: remove vlans
  hosts: switches
  gather_facts: no
  tasks:
    - name: remove vlan 10 and 20
      ios_vlans:
        config:
          - vlan_id: 10
          - vlan_id: 20
        state: deleted
...