---
- name: remove banners and loopback interface descriptions
  hosts: lab
  gather_facts: no
  tasks:
    - name: remove login banners
      ios_banner:
        banner: login
        state: absent

    - name: remove loopback interface descriptions
      ios_config:
        lines: no description
        parents: interface Loopback0

- name: remove vlans
  hosts: switches
  gather_facts: no
  tasks:
    - name: remove vlan 10 and 20
      ios_vlans:
        config:
          - vlan_id: 10
          - vlan_id: 20
        state: deleted

- name: remove vlan port assignments
  hosts: accessswitches
  gather_facts: no
  tasks:
    - name: remove vlan 10 assignment from GigabitEthernet 0/1
      ios_config:
        lines: switchport access vlan 1
        parents: interface GigabitEthernet 0/1
    
    - name: remove vlan 20 assignment from GigabitEthernet 0/2
      ios_config:
        lines: switchport access vlan 1
        parents: interface GigabitEthernet 0/2

- name: remove router on a stick configurations
  hosts: routers
  gather_facts: no
  tasks:
    - name: remove router on a stick sub-interfaces
      ios_config:
        lines:
          - no interface GigabitEthernet 0/0.10
          - no interface GigabitEthernet 0/0.20

- name: save configuration
  hosts: lab
  gather_facts: no
  tasks:
    - name: write
      ios_command:
        commands: write
...